### ISSUE TITLE
pico_gl: add a vertex step function

### ISSUE THREAD

**Issue by Tuhkis** [empyreanx/pico_headers#9]
Last time I didn't first open an issue. Sorry for that :D

I propose adding a "vertex step function" to describe to the gpu how to step through the data (step per vertex or step per instance) when rendering a buffer. (achieved through `glVertexAttribDivisor`) Also being able to render instances would logically follow this.

I have the code as local changes.

Cheers,
Tuhkis

**Comment by Tuhkis** [comment]
My local changes change buffer creation by adding in the vertex_step_function there. I made changes to the demo as well to reflect this.

**Comment by empyreanx** [comment]
I'm eager to see a PR. My understanding of glVertexAttribDivisor is hazy at best, perhaps it would help to see it in context. Feel free to implement instanced rendering as you see fit. You might be able to modify the existing draw functions, but I'll leave that up to you.

**Comment by Tuhkis** [comment]
I'll clean it up and submit a PR. There's some stuff I want your opinion on.

**Comment by Tuhkis** [comment]
I'll clean it up and submit a PR. There's some stuff I want your opinion on.
